# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
                            QMetaObject, QObject, QPoint, QRect,
                            QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
                           QFont, QFontDatabase, QGradient, QIcon,
                           QImage, QKeySequence, QLinearGradient, QPainter,
                           QPalette, QPixmap, QRadialGradient, QTransform, QStandardItemModel)
from PySide6.QtWidgets import (QApplication, QFrame, QHBoxLayout, QLabel,
                               QLineEdit, QMainWindow, QMenuBar, QPushButton,
                               QSizePolicy, QStatusBar, QWidget, QListView)

import pyqtgraph as pg


class custom_label(QLabel):
    def __init__(self, parent=None):
        super().__init__(parent)

    def setText(self, text):
        if len(self.text()) < 255:
            super().setText(text)
        else:
            super().setText('Maximum number of characters exceeded')


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 446)
        MainWindow.setMinimumSize(QSize(800, 446))
        MainWindow.setMaximumSize(QSize(800, 446))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.pushButton_7 = QPushButton(self.centralwidget)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(10, 140, 41, 51))
        self.pushButton_7.setMinimumSize(QSize(0, 51))
        self.pushButton_point = QPushButton(self.centralwidget)
        self.pushButton_point.setObjectName(u"pushButton_point")
        self.pushButton_point.setGeometry(QRect(90, 260, 41, 51))
        self.pushButton_5 = QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(50, 180, 41, 51))
        self.pushButton_5.setMinimumSize(QSize(0, 51))
        self.pushButton_minus = QPushButton(self.centralwidget)
        self.pushButton_minus.setObjectName(u"pushButton_minus")
        self.pushButton_minus.setGeometry(QRect(140, 220, 41, 51))
        self.pushButton_equal = QPushButton(self.centralwidget)
        self.pushButton_equal.setObjectName(u"pushButton_equal")
        self.pushButton_equal.setGeometry(QRect(230, 260, 41, 51))

        self.listView = QListView(self.centralwidget)
        self.listView.setObjectName(u"listView")
        self.listView.setGeometry(QRect(10, 350, 211, 70))

        self.model = QStandardItemModel(self.listView)
        self.listView.setModel(self.model)
        self.pushButton_clear_history = QPushButton(self.centralwidget)
        self.pushButton_clear_history.setObjectName(u"pushButton_clear_history")
        self.pushButton_clear_history.setText(u"CH")
        self.pushButton_clear_history.setGeometry(QRect(230, 365, 40, 40))

        self.pushButton_9 = QPushButton(self.centralwidget)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setGeometry(QRect(90, 140, 41, 51))
        self.pushButton_9.setMinimumSize(QSize(0, 51))
        self.pushButton_div = QPushButton(self.centralwidget)
        self.pushButton_div.setObjectName(u"pushButton_div")
        self.pushButton_div.setGeometry(QRect(140, 140, 41, 51))
        self.pushButton_8 = QPushButton(self.centralwidget)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(50, 140, 41, 51))
        self.pushButton_8.setMinimumSize(QSize(0, 51))
        self.pushButton_mul = QPushButton(self.centralwidget)
        self.pushButton_mul.setObjectName(u"pushButton_mul")
        self.pushButton_mul.setGeometry(QRect(140, 180, 41, 51))
        self.pushButton_0 = QPushButton(self.centralwidget)
        self.pushButton_0.setObjectName(u"pushButton_0")
        self.pushButton_0.setGeometry(QRect(50, 260, 41, 51))
        self.pushButton_0.setMinimumSize(QSize(0, 51))
        self.pushButton_6 = QPushButton(self.centralwidget)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(90, 180, 41, 51))
        self.pushButton_6.setMinimumSize(QSize(0, 51))
        self.pushButton_x = QPushButton(self.centralwidget)
        self.pushButton_x.setObjectName(u"pushButton_x")
        self.pushButton_x.setGeometry(QRect(10, 260, 41, 51))
        self.pushButton_1 = QPushButton(self.centralwidget)
        self.pushButton_1.setObjectName(u"pushButton_1")
        self.pushButton_1.setGeometry(QRect(10, 220, 41, 51))
        self.pushButton_1.setMinimumSize(QSize(0, 51))
        self.label = custom_label(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(0, 0, 291, 61))
        self.graphics_view = pg.PlotWidget(self.centralwidget)
        self.graphics_view.setObjectName(u"graphic")
        self.graphics_view.setMinimumSize(QSize(100, 300))
        self.graphics_view.setGeometry(QRect(400, 30, 300, 300))
        font = QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.pushButton_increase_font_size = QPushButton(self.centralwidget)
        self.pushButton_increase_font_size.setObjectName(u"pushButton_increase_font_size")
        self.pushButton_increase_font_size.setGeometry(QRect(280, 140, 100, 51))
        self.pushButton_increase_font_size.setText(QCoreApplication.translate("MainWindow", u"Increase Font Size", None))

        self.pushButton_decrease_font_size = QPushButton(self.centralwidget)
        self.pushButton_decrease_font_size.setObjectName(u"pushButton_decrease_font_size")
        self.pushButton_decrease_font_size.setGeometry(QRect(280, 200, 100, 51))
        self.pushButton_decrease_font_size.setText(QCoreApplication.translate("MainWindow", u"Decrease Font Size", None))


        self.label.setStyleSheet(u"gridline-color: rgb(255, 225, 230);")
        self.label.setFrameShape(QFrame.Panel)
        self.label.setFrameShadow(QFrame.Plain)
        self.label.setLineWidth(2)
        self.label.setMidLineWidth(1)
        self.label.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.pushButton_plus = QPushButton(self.centralwidget)
        self.pushButton_plus.setObjectName(u"pushButton_plus")
        self.pushButton_plus.setGeometry(QRect(140, 260, 41, 51))
        self.pushButton_3 = QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(90, 220, 41, 51))
        self.pushButton_3.setMinimumSize(QSize(0, 51))
        self.pushButton_4 = QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(10, 180, 41, 51))
        self.pushButton_4.setMinimumSize(QSize(0, 51))
        self.pushButton_2 = QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(50, 220, 41, 51))
        self.pushButton_2.setMinimumSize(QSize(0, 51))
        self.pushButton_sin = QPushButton(self.centralwidget)
        self.pushButton_sin.setObjectName(u"pushButton_sin")
        self.pushButton_sin.setGeometry(QRect(0, 70, 51, 32))
        self.pushButton_cos = QPushButton(self.centralwidget)
        self.pushButton_cos.setObjectName(u"pushButton_cos")
        self.pushButton_cos.setGeometry(QRect(60, 70, 51, 32))
        self.pushButton_tan = QPushButton(self.centralwidget)
        self.pushButton_tan.setObjectName(u"pushButton_tan")
        self.pushButton_tan.setGeometry(QRect(120, 70, 51, 32))
        self.pushButton_asin = QPushButton(self.centralwidget)
        self.pushButton_asin.setObjectName(u"pushButton_asin")
        self.pushButton_asin.setGeometry(QRect(0, 100, 51, 32))
        self.pushButton_acos = QPushButton(self.centralwidget)
        self.pushButton_acos.setObjectName(u"pushButton_acos")
        self.pushButton_acos.setGeometry(QRect(60, 100, 51, 32))
        self.pushButton_atan = QPushButton(self.centralwidget)
        self.pushButton_atan.setObjectName(u"pushButton_atan")
        self.pushButton_atan.setGeometry(QRect(120, 100, 51, 32))
        self.pushButton_sqrt = QPushButton(self.centralwidget)
        self.pushButton_sqrt.setObjectName(u"pushButton_sqrt")
        self.pushButton_sqrt.setGeometry(QRect(180, 70, 51, 32))
        self.pushButton_log = QPushButton(self.centralwidget)
        self.pushButton_log.setObjectName(u"pushButton_log")
        self.pushButton_log.setGeometry(QRect(180, 100, 51, 32))
        self.pushButton_ln = QPushButton(self.centralwidget)
        self.pushButton_ln.setObjectName(u"pushButton_ln")
        self.pushButton_ln.setGeometry(QRect(240, 70, 51, 32))
        self.pushButton_mod = QPushButton(self.centralwidget)
        self.pushButton_mod.setObjectName(u"pushButton_mod")
        self.pushButton_mod.setGeometry(QRect(240, 100, 51, 32))
        self.pushButton_bracket_open = QPushButton(self.centralwidget)
        self.pushButton_bracket_open.setObjectName(u"pushButton_bracket_open")
        self.pushButton_bracket_open.setGeometry(QRect(180, 140, 41, 51))
        self.pushButton_bracket_close = QPushButton(self.centralwidget)
        self.pushButton_bracket_close.setObjectName(u"pushButton_bracket_close")
        self.pushButton_bracket_close.setGeometry(QRect(180, 180, 41, 51))
        self.pushButton_clear = QPushButton(self.centralwidget)
        self.pushButton_clear.setObjectName(u"pushButton_clear")
        self.pushButton_clear.setGeometry(QRect(230, 180, 41, 51))
        self.pushButton_exp = QPushButton(self.centralwidget)
        self.pushButton_exp.setObjectName(u"pushButton_exp")
        self.pushButton_exp.setGeometry(QRect(180, 220, 41, 51))
        self.layoutWidget_4 = QWidget(self.centralwidget)
        self.layoutWidget_4.setObjectName(u"layoutWidget_4")
        self.layoutWidget_4.setGeometry(QRect(340, 360, 131, 26))
        self.horizontalLayout_6 = QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.label_7 = QLabel(self.layoutWidget_4)
        self.label_7.setObjectName(u"label_7")
        font1 = QFont()
        font1.setPointSize(14)
        self.label_7.setFont(font1)

        self.horizontalLayout_6.addWidget(self.label_7)

        self.line_y_max_2 = QLineEdit(self.layoutWidget_4)
        self.line_y_max_2.setObjectName(u"line_y_max_2")
        self.line_y_max_2.setMaxLength(5)

        self.horizontalLayout_6.addWidget(self.line_y_max_2)

        self.layoutWidget_3 = QWidget(self.centralwidget)
        self.layoutWidget_3.setObjectName(u"layoutWidget_3")
        self.layoutWidget_3.setGeometry(QRect(610, 330, 131, 26))
        self.horizontalLayout_7 = QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.label_9 = QLabel(self.layoutWidget_3)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setFont(font1)

        self.horizontalLayout_7.addWidget(self.label_9)

        self.line_x_min = QLineEdit(self.layoutWidget_3)
        self.line_x_min.setObjectName(u"line_x_min")
        self.line_x_min.setMaxLength(6)

        self.horizontalLayout_7.addWidget(self.line_x_min)

        self.layoutWidget_2 = QWidget(self.centralwidget)
        self.layoutWidget_2.setObjectName(u"layoutWidget_2")
        self.layoutWidget_2.setGeometry(QRect(340, 330, 131, 26))
        self.horizontalLayout_8 = QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_8.setObjectName(u"horizontalLayout_8")
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.label_10 = QLabel(self.layoutWidget_2)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setFont(font1)

        self.horizontalLayout_8.addWidget(self.label_10)
        self.pushButton_help = QPushButton(self.centralwidget)
        self.pushButton_help.setGeometry(QRect(720, 28, 50, 50))
        self.pushButton_help.setText('HELP')

        self.line_x_max_2 = QLineEdit(self.layoutWidget_2)
        self.line_x_max_2.setObjectName(u"line_x_max_2")
        self.line_x_max_2.setMaxLength(5)

        self.horizontalLayout_8.addWidget(self.line_x_max_2)

        self.layoutWidget_5 = QWidget(self.centralwidget)
        self.layoutWidget_5.setObjectName(u"layoutWidget_5")
        self.layoutWidget_5.setGeometry(QRect(610, 360, 131, 26))
        self.horizontalLayout_9 = QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_9.setObjectName(u"horizontalLayout_9")
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.label_11 = QLabel(self.layoutWidget_5)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setFont(font1)
        self.pushButton_credit = QPushButton(self.centralwidget)
        self.pushButton_credit.setGeometry(QRect(310,390, 100, 32))
        self.pushButton_credit.setText('credit')

        self.horizontalLayout_9.addWidget(self.label_11)

        self.line_y_min_2 = QLineEdit(self.layoutWidget_5)
        self.line_y_min_2.setObjectName(u"line_y_min_2")
        self.line_y_min_2.setMaxLength(6)

        self.horizontalLayout_9.addWidget(self.line_y_min_2)

        self.layoutWidget = QWidget(self.centralwidget)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(10, 310, 211, 26))
        self.horizontalLayout_10 = QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_10.setObjectName(u"horizontalLayout_10")
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.label_13 = QLabel(self.layoutWidget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setFont(font)

        self.horizontalLayout_10.addWidget(self.label_13)

        self.line_x = QLineEdit(self.layoutWidget)
        self.line_x.setObjectName(u"line_x")

        self.horizontalLayout_10.addWidget(self.line_x)

        self.pushButton_plot = QPushButton(self.centralwidget)
        self.pushButton_plot.setObjectName(u"pushButton_plot")
        self.pushButton_plot.setGeometry(QRect(490, 350, 100, 32))
        self.pushButton_delete_to_left_key = QPushButton(self.centralwidget)
        self.pushButton_delete_to_left_key.setObjectName(u"pushButton_delete_to_left_key")
        self.pushButton_delete_to_left_key.setGeometry(QRect(230, 140, 41, 51))
        self.pushButton_e = QPushButton(self.centralwidget)
        self.pushButton_e.setObjectName(u"pushButton_e")
        self.pushButton_e.setGeometry(QRect(180, 260, 41, 51))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 24))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)

    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.pushButton_7.setText(QCoreApplication.translate("MainWindow", u"7", None))
        self.pushButton_point.setText(QCoreApplication.translate("MainWindow", u".", None))
        self.pushButton_5.setText(QCoreApplication.translate("MainWindow", u"5", None))
        self.pushButton_minus.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.pushButton_equal.setText(QCoreApplication.translate("MainWindow", u"=", None))
        self.pushButton_9.setText(QCoreApplication.translate("MainWindow", u"9", None))
        self.pushButton_div.setText(QCoreApplication.translate("MainWindow", u"/", None))
        self.pushButton_8.setText(QCoreApplication.translate("MainWindow", u"8", None))
        self.pushButton_mul.setText(QCoreApplication.translate("MainWindow", u"*", None))
        self.pushButton_0.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.pushButton_6.setText(QCoreApplication.translate("MainWindow", u"6", None))
        self.pushButton_x.setText(QCoreApplication.translate("MainWindow", u"x", None))
        self.pushButton_1.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.pushButton_plus.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u"4", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.pushButton_sin.setText(QCoreApplication.translate("MainWindow", u"sin", None))
        self.pushButton_cos.setText(QCoreApplication.translate("MainWindow", u"cos", None))
        self.pushButton_tan.setText(QCoreApplication.translate("MainWindow", u"tan", None))
        self.pushButton_asin.setText(QCoreApplication.translate("MainWindow", u"asin", None))
        self.pushButton_acos.setText(QCoreApplication.translate("MainWindow", u"acos", None))
        self.pushButton_atan.setText(QCoreApplication.translate("MainWindow", u"atan", None))
        self.pushButton_sqrt.setText(QCoreApplication.translate("MainWindow", u"sqrt", None))
        self.pushButton_log.setText(QCoreApplication.translate("MainWindow", u"log", None))
        self.pushButton_ln.setText(QCoreApplication.translate("MainWindow", u"ln", None))
        self.pushButton_mod.setText(QCoreApplication.translate("MainWindow", u"%", None))
        self.pushButton_bracket_open.setText(QCoreApplication.translate("MainWindow", u"(", None))
        self.pushButton_bracket_close.setText(QCoreApplication.translate("MainWindow", u")", None))
        self.pushButton_clear.setText(QCoreApplication.translate("MainWindow", u"AC", None))
        self.pushButton_exp.setText(QCoreApplication.translate("MainWindow", u"^", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Y max =", None))
        self.line_y_max_2.setText(QCoreApplication.translate("MainWindow", u"10", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"X min =", None))
        self.line_x_min.setText(QCoreApplication.translate("MainWindow", u"-10", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"X max =", None))
        self.line_x_max_2.setText(QCoreApplication.translate("MainWindow", u"10", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Y min =", None))
        self.line_y_min_2.setText(QCoreApplication.translate("MainWindow", u"-10", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"X =", None))
        self.line_x.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.pushButton_plot.setText(QCoreApplication.translate("MainWindow", u"plot", None))
        self.pushButton_delete_to_left_key.setText(QCoreApplication.translate("MainWindow", u"\u232b", None))
        self.pushButton_e.setText(QCoreApplication.translate("MainWindow", u"e", None))
